### ISSUE TITLE
Adding skm_tools to PyPi

### ISSUE THREAD

**Issue by mbeavitt** [NIB-SI/skm-tools#2]
Hello,

I'm finding your tools really useful for exploring the curated datasets, and I was just wondering if you were planning to add the libraries to PyPi? It would be nice to be able to 'pip install' the tools so that they can be incorporated easily into other code without having to manually link the libraries with sys.path.append(<tools_path>).

**Comment by carissableker** [comment]
Hi! 

 I am not planning to add skm_tools to PyPI, but I can add a setup.py so that it can be installed using pip directly from the repo (cf https://pip.pypa.io/en/stable/topics/vcs-support/). 

Thanks for the suggestion!

**Comment by carissableker** [comment]
This should work for now:

    pip install "skm-tools[cytoscape,pdf] @ git+ssh://git@github.com/NIB-SI/skm-tools.git@issue2"

After some more testing, I'll merge the fix to the main branch and add install instructions to the README.

**Comment by mbeavitt** [comment]
TYSM!
